/*
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import finaproject.ui.internal.FinaprojectActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FinaprojectActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
