/*
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import finaproject.ui.internal.FinaprojectActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FinaprojectActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FinaprojectActivator activator = FinaprojectActivator.getInstance();
		return activator != null ? activator.getInjector(FinaprojectActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
