/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.SubscriberCallback;
import org.xtext.example.mydsl.myDsl.Topic;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Subscriber Callback</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubscriberCallbackImpl#getSubscribesTo <em>Subscribes To</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SubscriberCallbackImpl extends CallbackImpl implements SubscriberCallback
{
  /**
   * The cached value of the '{@link #getSubscribesTo() <em>Subscribes To</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubscribesTo()
   * @generated
   * @ordered
   */
  protected EList<Topic> subscribesTo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubscriberCallbackImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SUBSCRIBER_CALLBACK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Topic> getSubscribesTo()
  {
    if (subscribesTo == null)
    {
      subscribesTo = new EObjectResolvingEList<Topic>(Topic.class, this, MyDslPackage.SUBSCRIBER_CALLBACK__SUBSCRIBES_TO);
    }
    return subscribesTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBSCRIBER_CALLBACK__SUBSCRIBES_TO:
        return getSubscribesTo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBSCRIBER_CALLBACK__SUBSCRIBES_TO:
        getSubscribesTo().clear();
        getSubscribesTo().addAll((Collection<? extends Topic>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBSCRIBER_CALLBACK__SUBSCRIBES_TO:
        getSubscribesTo().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBSCRIBER_CALLBACK__SUBSCRIBES_TO:
        return subscribesTo != null && !subscribesTo.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SubscriberCallbackImpl
