/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Callback</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Callback#getBufferSize <em>Buffer Size</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Callback#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Callback#getExecutedIn <em>Executed In</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Callback#getExecutionTime <em>Execution Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCallback()
 * @model
 * @generated
 */
public interface Callback extends EObject
{
  /**
   * Returns the value of the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buffer Size</em>' attribute.
   * @see #setBufferSize(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCallback_BufferSize()
   * @model
   * @generated
   */
  int getBufferSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Callback#getBufferSize <em>Buffer Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Buffer Size</em>' attribute.
   * @see #getBufferSize()
   * @generated
   */
  void setBufferSize(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCallback_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Callback#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Executed In</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Executor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Executed In</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCallback_ExecutedIn()
   * @model
   * @generated
   */
  EList<Executor> getExecutedIn();

  /**
   * Returns the value of the '<em><b>Execution Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Execution Time</em>' attribute.
   * @see #setExecutionTime(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCallback_ExecutionTime()
   * @model
   * @generated
   */
  int getExecutionTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Callback#getExecutionTime <em>Execution Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Execution Time</em>' attribute.
   * @see #getExecutionTime()
   * @generated
   */
  void setExecutionTime(int value);

} // Callback
