/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Executor Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExecutorType()
 * @model
 * @generated
 */
public enum ExecutorType implements Enumerator
{
  /**
   * The '<em><b>SINGLETHREADED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SINGLETHREADED_VALUE
   * @generated
   * @ordered
   */
  SINGLETHREADED(0, "SINGLETHREADED", "SINGLETHREADED"),

  /**
   * The '<em><b>STATICSINGLETHREADED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STATICSINGLETHREADED_VALUE
   * @generated
   * @ordered
   */
  STATICSINGLETHREADED(1, "STATICSINGLETHREADED", "STATICSINGLETHREADED"),

  /**
   * The '<em><b>MULTITHREADED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MULTITHREADED_VALUE
   * @generated
   * @ordered
   */
  MULTITHREADED(2, "MULTITHREADED", "MULTITHREADED");

  /**
   * The '<em><b>SINGLETHREADED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SINGLETHREADED
   * @model
   * @generated
   * @ordered
   */
  public static final int SINGLETHREADED_VALUE = 0;

  /**
   * The '<em><b>STATICSINGLETHREADED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STATICSINGLETHREADED
   * @model
   * @generated
   * @ordered
   */
  public static final int STATICSINGLETHREADED_VALUE = 1;

  /**
   * The '<em><b>MULTITHREADED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MULTITHREADED
   * @model
   * @generated
   * @ordered
   */
  public static final int MULTITHREADED_VALUE = 2;

  /**
   * An array of all the '<em><b>Executor Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ExecutorType[] VALUES_ARRAY =
    new ExecutorType[]
    {
      SINGLETHREADED,
      STATICSINGLETHREADED,
      MULTITHREADED,
    };

  /**
   * A public read-only list of all the '<em><b>Executor Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ExecutorType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Executor Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ExecutorType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ExecutorType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Executor Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ExecutorType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ExecutorType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Executor Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ExecutorType get(int value)
  {
    switch (value)
    {
      case SINGLETHREADED_VALUE: return SINGLETHREADED;
      case STATICSINGLETHREADED_VALUE: return STATICSINGLETHREADED;
      case MULTITHREADED_VALUE: return MULTITHREADED;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ExecutorType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ExecutorType
