/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemModelImpl <em>System Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemModel()
   * @generated
   */
  int SYSTEM_MODEL = 0;

  /**
   * The feature id for the '<em><b>Systems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_MODEL__SYSTEMS = 0;

  /**
   * The number of structural features of the '<em>System Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 1;

  /**
   * The feature id for the '<em><b>System Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SYSTEM_NAME = 0;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__NODES = 1;

  /**
   * The feature id for the '<em><b>Topics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__TOPICS = 2;

  /**
   * The feature id for the '<em><b>Executors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__EXECUTORS = 3;

  /**
   * The feature id for the '<em><b>Services</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SERVICES = 4;

  /**
   * The feature id for the '<em><b>Periodictimers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__PERIODICTIMERS = 5;

  /**
   * The feature id for the '<em><b>Walltimers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__WALLTIMERS = 6;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NodeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNode()
   * @generated
   */
  int NODE = 2;

  /**
   * The feature id for the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODE_NAME = 0;

  /**
   * The feature id for the '<em><b>Publishers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__PUBLISHERS = 1;

  /**
   * The feature id for the '<em><b>Subscribers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__SUBSCRIBERS = 2;

  /**
   * The feature id for the '<em><b>Services</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__SERVICES = 3;

  /**
   * The feature id for the '<em><b>Servicerequests</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__SERVICEREQUESTS = 4;

  /**
   * The feature id for the '<em><b>Clients</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__CLIENTS = 5;

  /**
   * The feature id for the '<em><b>Timers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__TIMERS = 6;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CallbackImpl <em>Callback</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CallbackImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCallback()
   * @generated
   */
  int CALLBACK = 3;

  /**
   * The feature id for the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLBACK__BUFFER_SIZE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLBACK__NAME = 1;

  /**
   * The feature id for the '<em><b>Executed In</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLBACK__EXECUTED_IN = 2;

  /**
   * The feature id for the '<em><b>Execution Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLBACK__EXECUTION_TIME = 3;

  /**
   * The number of structural features of the '<em>Callback</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLBACK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExecutorImpl <em>Executor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExecutorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExecutor()
   * @generated
   */
  int EXECUTOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTOR__TYPE = 1;

  /**
   * The feature id for the '<em><b>Executed</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTOR__EXECUTED = 2;

  /**
   * The number of structural features of the '<em>Executor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceImpl <em>Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ServiceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getService()
   * @generated
   */
  int SERVICE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__NAME = 0;

  /**
   * The feature id for the '<em><b>Service Req</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__SERVICE_REQ = 1;

  /**
   * The feature id for the '<em><b>Client CAll</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__CLIENT_CALL = 2;

  /**
   * The feature id for the '<em><b>Service CAll</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__SERVICE_CALL = 3;

  /**
   * The number of structural features of the '<em>Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceRequestImpl <em>Service Request</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ServiceRequestImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getServiceRequest()
   * @generated
   */
  int SERVICE_REQUEST = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_REQUEST__NAME = 0;

  /**
   * The feature id for the '<em><b>Service</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_REQUEST__SERVICE = 1;

  /**
   * The number of structural features of the '<em>Service Request</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_REQUEST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TopicImpl <em>Topic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TopicImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTopic()
   * @generated
   */
  int TOPIC = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__NAME = 0;

  /**
   * The feature id for the '<em><b>Published</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__PUBLISHED = 1;

  /**
   * The feature id for the '<em><b>Subscribed</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__SUBSCRIBED = 2;

  /**
   * The number of structural features of the '<em>Topic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PublisherImpl <em>Publisher</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PublisherImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPublisher()
   * @generated
   */
  int PUBLISHER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUBLISHER__NAME = 0;

  /**
   * The feature id for the '<em><b>Publishes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUBLISHER__PUBLISHES = 1;

  /**
   * The feature id for the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUBLISHER__BUFFER_SIZE = 2;

  /**
   * The number of structural features of the '<em>Publisher</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUBLISHER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SubscriberCallbackImpl <em>Subscriber Callback</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SubscriberCallbackImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubscriberCallback()
   * @generated
   */
  int SUBSCRIBER_CALLBACK = 9;

  /**
   * The feature id for the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSCRIBER_CALLBACK__BUFFER_SIZE = CALLBACK__BUFFER_SIZE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSCRIBER_CALLBACK__NAME = CALLBACK__NAME;

  /**
   * The feature id for the '<em><b>Executed In</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSCRIBER_CALLBACK__EXECUTED_IN = CALLBACK__EXECUTED_IN;

  /**
   * The feature id for the '<em><b>Execution Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSCRIBER_CALLBACK__EXECUTION_TIME = CALLBACK__EXECUTION_TIME;

  /**
   * The feature id for the '<em><b>Subscribes To</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSCRIBER_CALLBACK__SUBSCRIBES_TO = CALLBACK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Subscriber Callback</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSCRIBER_CALLBACK_FEATURE_COUNT = CALLBACK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceCallbackImpl <em>Service Callback</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ServiceCallbackImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getServiceCallback()
   * @generated
   */
  int SERVICE_CALLBACK = 10;

  /**
   * The feature id for the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_CALLBACK__BUFFER_SIZE = CALLBACK__BUFFER_SIZE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_CALLBACK__NAME = CALLBACK__NAME;

  /**
   * The feature id for the '<em><b>Executed In</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_CALLBACK__EXECUTED_IN = CALLBACK__EXECUTED_IN;

  /**
   * The feature id for the '<em><b>Execution Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_CALLBACK__EXECUTION_TIME = CALLBACK__EXECUTION_TIME;

  /**
   * The feature id for the '<em><b>Service</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_CALLBACK__SERVICE = CALLBACK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Service Callback</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_CALLBACK_FEATURE_COUNT = CALLBACK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ClientCallbackImpl <em>Client Callback</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ClientCallbackImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClientCallback()
   * @generated
   */
  int CLIENT_CALLBACK = 11;

  /**
   * The feature id for the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIENT_CALLBACK__BUFFER_SIZE = CALLBACK__BUFFER_SIZE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIENT_CALLBACK__NAME = CALLBACK__NAME;

  /**
   * The feature id for the '<em><b>Executed In</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIENT_CALLBACK__EXECUTED_IN = CALLBACK__EXECUTED_IN;

  /**
   * The feature id for the '<em><b>Execution Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIENT_CALLBACK__EXECUTION_TIME = CALLBACK__EXECUTION_TIME;

  /**
   * The number of structural features of the '<em>Client Callback</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIENT_CALLBACK_FEATURE_COUNT = CALLBACK_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TimerCallbackImpl <em>Timer Callback</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TimerCallbackImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTimerCallback()
   * @generated
   */
  int TIMER_CALLBACK = 12;

  /**
   * The feature id for the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER_CALLBACK__BUFFER_SIZE = CALLBACK__BUFFER_SIZE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER_CALLBACK__NAME = CALLBACK__NAME;

  /**
   * The feature id for the '<em><b>Executed In</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER_CALLBACK__EXECUTED_IN = CALLBACK__EXECUTED_IN;

  /**
   * The feature id for the '<em><b>Execution Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER_CALLBACK__EXECUTION_TIME = CALLBACK__EXECUTION_TIME;

  /**
   * The feature id for the '<em><b>Of</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER_CALLBACK__OF = CALLBACK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Timer Callback</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER_CALLBACK_FEATURE_COUNT = CALLBACK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemTimerImpl <em>System Timer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemTimerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemTimer()
   * @generated
   */
  int SYSTEM_TIMER = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TIMER__NAME = 0;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TIMER__FROM = 1;

  /**
   * The feature id for the '<em><b>Systemtimer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TIMER__SYSTEMTIMER = 2;

  /**
   * The number of structural features of the '<em>System Timer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TIMER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PeriodicTimerImpl <em>Periodic Timer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PeriodicTimerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPeriodicTimer()
   * @generated
   */
  int PERIODIC_TIMER = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODIC_TIMER__NAME = SYSTEM_TIMER__NAME;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODIC_TIMER__FROM = SYSTEM_TIMER__FROM;

  /**
   * The feature id for the '<em><b>Systemtimer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODIC_TIMER__SYSTEMTIMER = SYSTEM_TIMER__SYSTEMTIMER;

  /**
   * The feature id for the '<em><b>Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODIC_TIMER__PERIOD = SYSTEM_TIMER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Periodic Timer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODIC_TIMER_FEATURE_COUNT = SYSTEM_TIMER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WalltimerImpl <em>Walltimer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WalltimerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWalltimer()
   * @generated
   */
  int WALLTIMER = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALLTIMER__NAME = SYSTEM_TIMER__NAME;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALLTIMER__FROM = SYSTEM_TIMER__FROM;

  /**
   * The feature id for the '<em><b>Systemtimer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALLTIMER__SYSTEMTIMER = SYSTEM_TIMER__SYSTEMTIMER;

  /**
   * The feature id for the '<em><b>Release Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALLTIMER__RELEASE_TIMES = SYSTEM_TIMER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Walltimer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALLTIMER_FEATURE_COUNT = SYSTEM_TIMER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.ExecutorType <em>Executor Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.ExecutorType
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExecutorType()
   * @generated
   */
  int EXECUTOR_TYPE = 16;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SystemModel <em>System Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemModel
   * @generated
   */
  EClass getSystemModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SystemModel#getSystems <em>Systems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Systems</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemModel#getSystems()
   * @see #getSystemModel()
   * @generated
   */
  EReference getSystemModel_Systems();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.xtext.example.mydsl.myDsl.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.System#getSystemName <em>System Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>System Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getSystemName()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_SystemName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.System#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getNodes()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Nodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.System#getTopics <em>Topics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Topics</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getTopics()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Topics();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.System#getExecutors <em>Executors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Executors</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getExecutors()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Executors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.System#getServices <em>Services</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Services</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getServices()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Services();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.System#getPeriodictimers <em>Periodictimers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Periodictimers</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getPeriodictimers()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Periodictimers();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.System#getWalltimers <em>Walltimers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Walltimers</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getWalltimers()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Walltimers();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Node#getNodeName <em>Node Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getNodeName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_NodeName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Node#getPublishers <em>Publishers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Publishers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getPublishers()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Publishers();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Node#getSubscribers <em>Subscribers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subscribers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getSubscribers()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Subscribers();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Node#getServices <em>Services</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Services</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getServices()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Services();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Node#getServicerequests <em>Servicerequests</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servicerequests</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getServicerequests()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Servicerequests();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Node#getClients <em>Clients</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clients</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getClients()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Clients();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Node#getTimers <em>Timers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Timers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getTimers()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Timers();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Callback <em>Callback</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Callback</em>'.
   * @see org.xtext.example.mydsl.myDsl.Callback
   * @generated
   */
  EClass getCallback();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Callback#getBufferSize <em>Buffer Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Buffer Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Callback#getBufferSize()
   * @see #getCallback()
   * @generated
   */
  EAttribute getCallback_BufferSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Callback#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Callback#getName()
   * @see #getCallback()
   * @generated
   */
  EAttribute getCallback_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Callback#getExecutedIn <em>Executed In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Executed In</em>'.
   * @see org.xtext.example.mydsl.myDsl.Callback#getExecutedIn()
   * @see #getCallback()
   * @generated
   */
  EReference getCallback_ExecutedIn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Callback#getExecutionTime <em>Execution Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Execution Time</em>'.
   * @see org.xtext.example.mydsl.myDsl.Callback#getExecutionTime()
   * @see #getCallback()
   * @generated
   */
  EAttribute getCallback_ExecutionTime();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Executor <em>Executor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Executor</em>'.
   * @see org.xtext.example.mydsl.myDsl.Executor
   * @generated
   */
  EClass getExecutor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Executor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Executor#getName()
   * @see #getExecutor()
   * @generated
   */
  EAttribute getExecutor_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Executor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Executor#getType()
   * @see #getExecutor()
   * @generated
   */
  EAttribute getExecutor_Type();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Executor#getExecuted <em>Executed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Executed</em>'.
   * @see org.xtext.example.mydsl.myDsl.Executor#getExecuted()
   * @see #getExecutor()
   * @generated
   */
  EReference getExecutor_Executed();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Service <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service</em>'.
   * @see org.xtext.example.mydsl.myDsl.Service
   * @generated
   */
  EClass getService();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Service#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Service#getName()
   * @see #getService()
   * @generated
   */
  EAttribute getService_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Service#getServiceReq <em>Service Req</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Service Req</em>'.
   * @see org.xtext.example.mydsl.myDsl.Service#getServiceReq()
   * @see #getService()
   * @generated
   */
  EReference getService_ServiceReq();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Service#getClientCAll <em>Client CAll</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Client CAll</em>'.
   * @see org.xtext.example.mydsl.myDsl.Service#getClientCAll()
   * @see #getService()
   * @generated
   */
  EReference getService_ClientCAll();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Service#getServiceCAll <em>Service CAll</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Service CAll</em>'.
   * @see org.xtext.example.mydsl.myDsl.Service#getServiceCAll()
   * @see #getService()
   * @generated
   */
  EReference getService_ServiceCAll();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ServiceRequest <em>Service Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service Request</em>'.
   * @see org.xtext.example.mydsl.myDsl.ServiceRequest
   * @generated
   */
  EClass getServiceRequest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ServiceRequest#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ServiceRequest#getName()
   * @see #getServiceRequest()
   * @generated
   */
  EAttribute getServiceRequest_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.ServiceRequest#getService <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Service</em>'.
   * @see org.xtext.example.mydsl.myDsl.ServiceRequest#getService()
   * @see #getServiceRequest()
   * @generated
   */
  EReference getServiceRequest_Service();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Topic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Topic</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topic
   * @generated
   */
  EClass getTopic();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Topic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topic#getName()
   * @see #getTopic()
   * @generated
   */
  EAttribute getTopic_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Topic#getPublished <em>Published</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Published</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topic#getPublished()
   * @see #getTopic()
   * @generated
   */
  EReference getTopic_Published();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Topic#getSubscribed <em>Subscribed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Subscribed</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topic#getSubscribed()
   * @see #getTopic()
   * @generated
   */
  EReference getTopic_Subscribed();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Publisher <em>Publisher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Publisher</em>'.
   * @see org.xtext.example.mydsl.myDsl.Publisher
   * @generated
   */
  EClass getPublisher();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Publisher#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Publisher#getName()
   * @see #getPublisher()
   * @generated
   */
  EAttribute getPublisher_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Publisher#getPublishes <em>Publishes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Publishes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Publisher#getPublishes()
   * @see #getPublisher()
   * @generated
   */
  EReference getPublisher_Publishes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Publisher#getBufferSize <em>Buffer Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Buffer Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Publisher#getBufferSize()
   * @see #getPublisher()
   * @generated
   */
  EAttribute getPublisher_BufferSize();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SubscriberCallback <em>Subscriber Callback</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subscriber Callback</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubscriberCallback
   * @generated
   */
  EClass getSubscriberCallback();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.SubscriberCallback#getSubscribesTo <em>Subscribes To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Subscribes To</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubscriberCallback#getSubscribesTo()
   * @see #getSubscriberCallback()
   * @generated
   */
  EReference getSubscriberCallback_SubscribesTo();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ServiceCallback <em>Service Callback</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service Callback</em>'.
   * @see org.xtext.example.mydsl.myDsl.ServiceCallback
   * @generated
   */
  EClass getServiceCallback();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.ServiceCallback#getService <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Service</em>'.
   * @see org.xtext.example.mydsl.myDsl.ServiceCallback#getService()
   * @see #getServiceCallback()
   * @generated
   */
  EReference getServiceCallback_Service();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ClientCallback <em>Client Callback</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Client Callback</em>'.
   * @see org.xtext.example.mydsl.myDsl.ClientCallback
   * @generated
   */
  EClass getClientCallback();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.TimerCallback <em>Timer Callback</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Timer Callback</em>'.
   * @see org.xtext.example.mydsl.myDsl.TimerCallback
   * @generated
   */
  EClass getTimerCallback();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.TimerCallback#getOf <em>Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Of</em>'.
   * @see org.xtext.example.mydsl.myDsl.TimerCallback#getOf()
   * @see #getTimerCallback()
   * @generated
   */
  EReference getTimerCallback_Of();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SystemTimer <em>System Timer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Timer</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemTimer
   * @generated
   */
  EClass getSystemTimer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SystemTimer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemTimer#getName()
   * @see #getSystemTimer()
   * @generated
   */
  EAttribute getSystemTimer_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.SystemTimer#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemTimer#getFrom()
   * @see #getSystemTimer()
   * @generated
   */
  EReference getSystemTimer_From();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SystemTimer#getSystemtimer <em>Systemtimer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Systemtimer</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemTimer#getSystemtimer()
   * @see #getSystemTimer()
   * @generated
   */
  EReference getSystemTimer_Systemtimer();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.PeriodicTimer <em>Periodic Timer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Periodic Timer</em>'.
   * @see org.xtext.example.mydsl.myDsl.PeriodicTimer
   * @generated
   */
  EClass getPeriodicTimer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PeriodicTimer#getPeriod <em>Period</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Period</em>'.
   * @see org.xtext.example.mydsl.myDsl.PeriodicTimer#getPeriod()
   * @see #getPeriodicTimer()
   * @generated
   */
  EAttribute getPeriodicTimer_Period();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Walltimer <em>Walltimer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Walltimer</em>'.
   * @see org.xtext.example.mydsl.myDsl.Walltimer
   * @generated
   */
  EClass getWalltimer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Walltimer#getReleaseTimes <em>Release Times</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Release Times</em>'.
   * @see org.xtext.example.mydsl.myDsl.Walltimer#getReleaseTimes()
   * @see #getWalltimer()
   * @generated
   */
  EAttribute getWalltimer_ReleaseTimes();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.ExecutorType <em>Executor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Executor Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExecutorType
   * @generated
   */
  EEnum getExecutorType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemModelImpl <em>System Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemModel()
     * @generated
     */
    EClass SYSTEM_MODEL = eINSTANCE.getSystemModel();

    /**
     * The meta object literal for the '<em><b>Systems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_MODEL__SYSTEMS = eINSTANCE.getSystemModel_Systems();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>System Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__SYSTEM_NAME = eINSTANCE.getSystem_SystemName();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__NODES = eINSTANCE.getSystem_Nodes();

    /**
     * The meta object literal for the '<em><b>Topics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__TOPICS = eINSTANCE.getSystem_Topics();

    /**
     * The meta object literal for the '<em><b>Executors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__EXECUTORS = eINSTANCE.getSystem_Executors();

    /**
     * The meta object literal for the '<em><b>Services</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SERVICES = eINSTANCE.getSystem_Services();

    /**
     * The meta object literal for the '<em><b>Periodictimers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__PERIODICTIMERS = eINSTANCE.getSystem_Periodictimers();

    /**
     * The meta object literal for the '<em><b>Walltimers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__WALLTIMERS = eINSTANCE.getSystem_Walltimers();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NodeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Node Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NODE_NAME = eINSTANCE.getNode_NodeName();

    /**
     * The meta object literal for the '<em><b>Publishers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__PUBLISHERS = eINSTANCE.getNode_Publishers();

    /**
     * The meta object literal for the '<em><b>Subscribers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__SUBSCRIBERS = eINSTANCE.getNode_Subscribers();

    /**
     * The meta object literal for the '<em><b>Services</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__SERVICES = eINSTANCE.getNode_Services();

    /**
     * The meta object literal for the '<em><b>Servicerequests</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__SERVICEREQUESTS = eINSTANCE.getNode_Servicerequests();

    /**
     * The meta object literal for the '<em><b>Clients</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__CLIENTS = eINSTANCE.getNode_Clients();

    /**
     * The meta object literal for the '<em><b>Timers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__TIMERS = eINSTANCE.getNode_Timers();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CallbackImpl <em>Callback</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CallbackImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCallback()
     * @generated
     */
    EClass CALLBACK = eINSTANCE.getCallback();

    /**
     * The meta object literal for the '<em><b>Buffer Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLBACK__BUFFER_SIZE = eINSTANCE.getCallback_BufferSize();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLBACK__NAME = eINSTANCE.getCallback_Name();

    /**
     * The meta object literal for the '<em><b>Executed In</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALLBACK__EXECUTED_IN = eINSTANCE.getCallback_ExecutedIn();

    /**
     * The meta object literal for the '<em><b>Execution Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLBACK__EXECUTION_TIME = eINSTANCE.getCallback_ExecutionTime();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExecutorImpl <em>Executor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExecutorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExecutor()
     * @generated
     */
    EClass EXECUTOR = eINSTANCE.getExecutor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXECUTOR__NAME = eINSTANCE.getExecutor_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXECUTOR__TYPE = eINSTANCE.getExecutor_Type();

    /**
     * The meta object literal for the '<em><b>Executed</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXECUTOR__EXECUTED = eINSTANCE.getExecutor_Executed();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceImpl <em>Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ServiceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getService()
     * @generated
     */
    EClass SERVICE = eINSTANCE.getService();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICE__NAME = eINSTANCE.getService_Name();

    /**
     * The meta object literal for the '<em><b>Service Req</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__SERVICE_REQ = eINSTANCE.getService_ServiceReq();

    /**
     * The meta object literal for the '<em><b>Client CAll</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__CLIENT_CALL = eINSTANCE.getService_ClientCAll();

    /**
     * The meta object literal for the '<em><b>Service CAll</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__SERVICE_CALL = eINSTANCE.getService_ServiceCAll();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceRequestImpl <em>Service Request</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ServiceRequestImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getServiceRequest()
     * @generated
     */
    EClass SERVICE_REQUEST = eINSTANCE.getServiceRequest();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICE_REQUEST__NAME = eINSTANCE.getServiceRequest_Name();

    /**
     * The meta object literal for the '<em><b>Service</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE_REQUEST__SERVICE = eINSTANCE.getServiceRequest_Service();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TopicImpl <em>Topic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TopicImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTopic()
     * @generated
     */
    EClass TOPIC = eINSTANCE.getTopic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOPIC__NAME = eINSTANCE.getTopic_Name();

    /**
     * The meta object literal for the '<em><b>Published</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOPIC__PUBLISHED = eINSTANCE.getTopic_Published();

    /**
     * The meta object literal for the '<em><b>Subscribed</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOPIC__SUBSCRIBED = eINSTANCE.getTopic_Subscribed();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PublisherImpl <em>Publisher</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PublisherImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPublisher()
     * @generated
     */
    EClass PUBLISHER = eINSTANCE.getPublisher();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUBLISHER__NAME = eINSTANCE.getPublisher_Name();

    /**
     * The meta object literal for the '<em><b>Publishes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUBLISHER__PUBLISHES = eINSTANCE.getPublisher_Publishes();

    /**
     * The meta object literal for the '<em><b>Buffer Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUBLISHER__BUFFER_SIZE = eINSTANCE.getPublisher_BufferSize();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SubscriberCallbackImpl <em>Subscriber Callback</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SubscriberCallbackImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubscriberCallback()
     * @generated
     */
    EClass SUBSCRIBER_CALLBACK = eINSTANCE.getSubscriberCallback();

    /**
     * The meta object literal for the '<em><b>Subscribes To</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBSCRIBER_CALLBACK__SUBSCRIBES_TO = eINSTANCE.getSubscriberCallback_SubscribesTo();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceCallbackImpl <em>Service Callback</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ServiceCallbackImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getServiceCallback()
     * @generated
     */
    EClass SERVICE_CALLBACK = eINSTANCE.getServiceCallback();

    /**
     * The meta object literal for the '<em><b>Service</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE_CALLBACK__SERVICE = eINSTANCE.getServiceCallback_Service();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ClientCallbackImpl <em>Client Callback</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ClientCallbackImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClientCallback()
     * @generated
     */
    EClass CLIENT_CALLBACK = eINSTANCE.getClientCallback();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TimerCallbackImpl <em>Timer Callback</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TimerCallbackImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTimerCallback()
     * @generated
     */
    EClass TIMER_CALLBACK = eINSTANCE.getTimerCallback();

    /**
     * The meta object literal for the '<em><b>Of</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIMER_CALLBACK__OF = eINSTANCE.getTimerCallback_Of();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemTimerImpl <em>System Timer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemTimerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemTimer()
     * @generated
     */
    EClass SYSTEM_TIMER = eINSTANCE.getSystemTimer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_TIMER__NAME = eINSTANCE.getSystemTimer_Name();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_TIMER__FROM = eINSTANCE.getSystemTimer_From();

    /**
     * The meta object literal for the '<em><b>Systemtimer</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_TIMER__SYSTEMTIMER = eINSTANCE.getSystemTimer_Systemtimer();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PeriodicTimerImpl <em>Periodic Timer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PeriodicTimerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPeriodicTimer()
     * @generated
     */
    EClass PERIODIC_TIMER = eINSTANCE.getPeriodicTimer();

    /**
     * The meta object literal for the '<em><b>Period</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERIODIC_TIMER__PERIOD = eINSTANCE.getPeriodicTimer_Period();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WalltimerImpl <em>Walltimer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WalltimerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWalltimer()
     * @generated
     */
    EClass WALLTIMER = eINSTANCE.getWalltimer();

    /**
     * The meta object literal for the '<em><b>Release Times</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WALLTIMER__RELEASE_TIMES = eINSTANCE.getWalltimer_ReleaseTimes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.ExecutorType <em>Executor Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.ExecutorType
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExecutorType()
     * @generated
     */
    EEnum EXECUTOR_TYPE = eINSTANCE.getExecutorType();

  }

} //MyDslPackage
