/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Node#getNodeName <em>Node Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Node#getPublishers <em>Publishers</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Node#getSubscribers <em>Subscribers</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Node#getServices <em>Services</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Node#getServicerequests <em>Servicerequests</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Node#getClients <em>Clients</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Node#getTimers <em>Timers</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Name</em>' attribute.
   * @see #setNodeName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode_NodeName()
   * @model
   * @generated
   */
  String getNodeName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Node#getNodeName <em>Node Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Name</em>' attribute.
   * @see #getNodeName()
   * @generated
   */
  void setNodeName(String value);

  /**
   * Returns the value of the '<em><b>Publishers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Publisher}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Publishers</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode_Publishers()
   * @model containment="true"
   * @generated
   */
  EList<Publisher> getPublishers();

  /**
   * Returns the value of the '<em><b>Subscribers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.SubscriberCallback}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subscribers</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode_Subscribers()
   * @model containment="true"
   * @generated
   */
  EList<SubscriberCallback> getSubscribers();

  /**
   * Returns the value of the '<em><b>Services</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ServiceCallback}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Services</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode_Services()
   * @model containment="true"
   * @generated
   */
  EList<ServiceCallback> getServices();

  /**
   * Returns the value of the '<em><b>Servicerequests</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ServiceRequest}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Servicerequests</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode_Servicerequests()
   * @model containment="true"
   * @generated
   */
  EList<ServiceRequest> getServicerequests();

  /**
   * Returns the value of the '<em><b>Clients</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ClientCallback}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clients</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode_Clients()
   * @model containment="true"
   * @generated
   */
  EList<ClientCallback> getClients();

  /**
   * Returns the value of the '<em><b>Timers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.TimerCallback}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timers</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNode_Timers()
   * @model containment="true"
   * @generated
   */
  EList<TimerCallback> getTimers();

} // Node
