/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Publisher</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Publisher#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Publisher#getPublishes <em>Publishes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Publisher#getBufferSize <em>Buffer Size</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPublisher()
 * @model
 * @generated
 */
public interface Publisher extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPublisher_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Publisher#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Publishes</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Topic}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Publishes</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPublisher_Publishes()
   * @model
   * @generated
   */
  EList<Topic> getPublishes();

  /**
   * Returns the value of the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buffer Size</em>' attribute.
   * @see #setBufferSize(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPublisher_BufferSize()
   * @model
   * @generated
   */
  int getBufferSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Publisher#getBufferSize <em>Buffer Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Buffer Size</em>' attribute.
   * @see #getBufferSize()
   * @generated
   */
  void setBufferSize(int value);

} // Publisher
