/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subscriber Callback</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SubscriberCallback#getSubscribesTo <em>Subscribes To</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubscriberCallback()
 * @model
 * @generated
 */
public interface SubscriberCallback extends Callback
{
  /**
   * Returns the value of the '<em><b>Subscribes To</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Topic}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subscribes To</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubscriberCallback_SubscribesTo()
   * @model
   * @generated
   */
  EList<Topic> getSubscribesTo();

} // SubscriberCallback
