/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getSystemName <em>System Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getNodes <em>Nodes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getTopics <em>Topics</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getExecutors <em>Executors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getServices <em>Services</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getPeriodictimers <em>Periodictimers</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getWalltimers <em>Walltimers</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends EObject
{
  /**
   * Returns the value of the '<em><b>System Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>System Name</em>' attribute.
   * @see #setSystemName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_SystemName()
   * @model
   * @generated
   */
  String getSystemName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.System#getSystemName <em>System Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System Name</em>' attribute.
   * @see #getSystemName()
   * @generated
   */
  void setSystemName(String value);

  /**
   * Returns the value of the '<em><b>Nodes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Node}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_Nodes()
   * @model containment="true"
   * @generated
   */
  EList<Node> getNodes();

  /**
   * Returns the value of the '<em><b>Topics</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Topic}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Topics</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_Topics()
   * @model containment="true"
   * @generated
   */
  EList<Topic> getTopics();

  /**
   * Returns the value of the '<em><b>Executors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Executor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Executors</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_Executors()
   * @model containment="true"
   * @generated
   */
  EList<Executor> getExecutors();

  /**
   * Returns the value of the '<em><b>Services</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Service}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Services</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_Services()
   * @model containment="true"
   * @generated
   */
  EList<Service> getServices();

  /**
   * Returns the value of the '<em><b>Periodictimers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.PeriodicTimer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Periodictimers</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_Periodictimers()
   * @model containment="true"
   * @generated
   */
  EList<PeriodicTimer> getPeriodictimers();

  /**
   * Returns the value of the '<em><b>Walltimers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Walltimer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Walltimers</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_Walltimers()
   * @model containment="true"
   * @generated
   */
  EList<Walltimer> getWalltimers();

} // System
