/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Timer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SystemTimer#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SystemTimer#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SystemTimer#getSystemtimer <em>Systemtimer</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemTimer()
 * @model
 * @generated
 */
public interface SystemTimer extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemTimer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SystemTimer#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(TimerCallback)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemTimer_From()
   * @model
   * @generated
   */
  TimerCallback getFrom();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SystemTimer#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(TimerCallback value);

  /**
   * Returns the value of the '<em><b>Systemtimer</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.SystemTimer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Systemtimer</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemTimer_Systemtimer()
   * @model containment="true"
   * @generated
   */
  EList<SystemTimer> getSystemtimer();

} // SystemTimer
