/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timer Callback</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TimerCallback#getOf <em>Of</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTimerCallback()
 * @model
 * @generated
 */
public interface TimerCallback extends Callback
{
  /**
   * Returns the value of the '<em><b>Of</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Of</em>' reference.
   * @see #setOf(SystemTimer)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTimerCallback_Of()
   * @model
   * @generated
   */
  SystemTimer getOf();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TimerCallback#getOf <em>Of</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Of</em>' reference.
   * @see #getOf()
   * @generated
   */
  void setOf(SystemTimer value);

} // TimerCallback
