/**
 * generated by Xtext 2.36.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Topic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Topic#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Topic#getPublished <em>Published</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Topic#getSubscribed <em>Subscribed</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTopic()
 * @model
 * @generated
 */
public interface Topic extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTopic_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Topic#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Published</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Publisher}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Published</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTopic_Published()
   * @model
   * @generated
   */
  EList<Publisher> getPublished();

  /**
   * Returns the value of the '<em><b>Subscribed</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.SubscriberCallback}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subscribed</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTopic_Subscribed()
   * @model
   * @generated
   */
  EList<SubscriberCallback> getSubscribed();

} // Topic
